### PR TITLE
Add: Skip specific towers within the kings tower

### PR DESCRIPTION
**Pull request by FallenKN**
Due to being powercapped in specific towers running the script would get me stuck in specific towers on my account.
I am unsure how hard it would be to detect that so I added the ability to skip specific tower stages instead.

### CODE REVIEW

**Comment by kevingrillet** [comment]
Why not just put `maxKingsTowerFights=0` or `1`?

Mmh, the script would be able to detect it with a little add in the config which would check the number of victories in every towers... then if it was 0 save the date to something and a check could tell do not try this tower until another month, or a level up, but it's way too far from the level of intelligence of the current script 😉

Many bools work fine too 😉 
I think you could check your test first to avoid 2 check when the tower is open and you don't want to do it.

```sh
        if [ "$doTowerOfLight" = true ] && { [ "$dayofweek" -eq 1 ] || [ "$dayofweek" -eq 5 ] || [ "$dayofweek" -eq 7 ] ;}; then
            printInColor "INFO" "Tower of Light $(kingsTower_battle 300 950)" # Tower of Light
        fi
```
*A bit less than 130 chars :tada: Or break the line using `\`*

Example:

```cmd
$ if [ 0 = 1 ] && { [ 0 = 0 ] || [ 0 = 0 ] ;}; then echo "OK"; fi

$ if [ 0 = 0 ] && { [ 0 = 0 ] || [ 0 = 0 ] ;}; then echo "OK"; fi
OK

$ if [ 0 = 0 ] && { [ 0 = 0 ] || [ 0 = 1 ] ;}; then echo "OK"; fi
OK

$ if [ 0 = 0 ] && { [ 0 = 1 ] || [ 0 = 1 ] ;}; then echo "OK"; fi

```

**Comment by FallenKN** [comment]
> Why not just put maxKingsTowerFights=0 or 1?
Because I still want the script to attempt the towers that I can attempt to fight in :D

> I think you could check your test first to avoid 2 check when the tower is open and you don't want to do it.
Sounds good :P

**Comment by Zebiano** [comment]
Interesting problem we got here. What is keeping you from fighting in the towers @FallenKN? Is it VIP Level, heroes or maybe a certain stage you need to complete in the campaign?

This is honestly a problem that shouldn't be solved this way. Instead, we need to add a `config.ini` variable that asks for the users' VIP level. Depending on that level, the script acts accordingly. But for now, this will do, as I highly doubt we'll get something like this in the near future, or ever.

The PR seems good to me, I've tested it and it's working. Thank you very much for considering all the different places where to update the info! I appreciate that a lot.

**Comment by Zebiano** [comment]
Also, I did not understand your example @kevingrillet:

> ```
> $ if [ 0 = 1 ] && { [ 0 = 0 ] || [ 0 = 0 ] ;}; then echo "OK"; fi
> 
> $ if [ 0 = 0 ] && { [ 0 = 0 ] || [ 0 = 0 ] ;}; then echo "OK"; fi
> OK
> 
> $ if [ 0 = 0 ] && { [ 0 = 0 ] || [ 0 = 1 ] ;}; then echo "OK"; fi
> OK
> 
> $ if [ 0 = 0 ] && { [ 0 = 1 ] || [ 0 = 1 ] ;}; then echo "OK"; fi
> ```
I cannot spot the difference, besides two `OK`s below the middle lines. What am I missing here?

Either way, not all of them are under 130 chars, which is quite unfortunate. I do not like to line break them like that simply because of a max limit. But I guess rules are rules... 😅

**Comment by kevingrillet** [comment]
> I cannot spot the difference, besides two `OK`s below the middle lines. What am I missing here?

The difference and the 2nd and 3rd one is to show that the `||` is still working, so nothing important 😉 

> Either way, not all of them are under 130 chars, which is quite unfortunate. I do not like to line break them like that simply because of a max limit. But I guess rules are rules... 😅

Being a bit over 130 chars is not a problem, it's just a bad habit 🙈

**Comment by Zebiano** [comment]
> Being a bit over 130 chars is not a problem, it's just a bad habit 🙈

You are right, and that's exactly why I've decided to remove the line breaks! :smile:

I prefer it way more in one line in this case.

**Comment by Zebiano** [comment]
Thank you very much for this PR @FallenKN! I appreciate it a lot when people take part in the project and make it a better one.

**Pull request merged**
