### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by kevingrillet**
- Shop limited offer
- Shop weekly lab
- Summon

### CODE REVIEW

**Comment by Zebiano** [comment]
Successfully tested changes besides the Test Server ones, as I do not have a test Server account. Thank you for this PR!

**Comment by kevingrillet** [comment]
Mmh, I forgot to update the normal shop too 😸 
I'll do it tomorrow

**Comment by Zebiano** [comment]
But it worked...? 😅 

I tested the shop on my account, not the test server.

**Comment by kevingrillet** [comment]
It's the weekly lab store that required an update :D

**Pull request merged**
