### PR TITLE
Add: Beat Campaign Every 3 Days (Mythic Trick)

### PR DESCRIPTION
**Pull request by delgatojr**
Will beat the Campaign Every three days.
Waiting three days will give better rewards like mythic armor or upgrade stones, because of a pity timer.
Tested with single battles, multi-battles, edited temp file to be over 3 days, under 3 days.

### CODE REVIEW

**Comment by delgatojr** [comment]
Maybe add output that shows that it it beat the campaign? Not sure where I would put it.

**Comment by delgatojr** [comment]
Also, should it beat the campaign when the file that holds the date doesn't exist? Or should it still wait 3 days?

**Comment by Zebiano** [comment]
> Maybe add output that shows that it beat the campaign? Not sure where I would put it.

Sounds like a good idea. I'll add a commit soon adding this in case you haven't yet.

> Also, should it beat the campaign when the file that holds the date doesn't exist? Or should it still wait 3 days?

I think it should try to beat it.

**Comment by kevingrillet** [comment]
The day of the fight, it should try to advance until the defeat (in option of course) because by doing the Mythic Trick, and not pushing you will end with too low resources to level up past a certain time... but i like the idea 👍

**Comment by Zebiano** [comment]
> It should try to advance until the defeat

Yeah, you're right! Ideally, it would work this way. I'll see if I can do something about that...

**Comment by Zebiano** [comment]
Could you test this out again @delgatojr? I've made some changes and I can't test multi-battle stages. Currently, the script exits after trying to battle in the campaign, so it's already testable out of the box!

Also, could you send me an RGB value and the respective coordinates of the blue `Confirm` button when you try to fight in a multi-battle stage? This happens when you have saved progress, though hit the `Return` arrow and it asks you if you're sure you want to exit. I'd rather test for the button than test if the script is back at the Campaign Tab (home as you called it).

If multi-stage battles work still, I just need to update that RGB value I just asked you to and this PR should be ready!

**Comment by delgatojr** [comment]
I could see a future error the first time encountering a multi-battle, or like going from 3 multi-battles to 4 multi-battles. There is no line-up already setup on on that new second battle, or new third battle, etc. You'll have to manually add heroes to the lineup, then the game will save the line-up for future multi-battles.

> Also, could you send me an RGB value and the respective coordinates of the blue `Confirm` button when you try to fight in a multi-battle stage? 

Coordinates: 715 1260
RGB: feffff
It's directly on the white "f" in "confirm"

**Comment by delgatojr** [comment]
And another issue could be with multiple account. If it's been 3 days, it will only do Mythic Trick on the first account/first script run. Add feature for multiple accounts?

**Comment by Zebiano** [comment]
> future error the first time encountering a multi-battle

I'm imagining this will be OK as the script will probably be waiting for the battle to be over, so the user just has to start it and then the script will keep on doing its thing when the battle is over.

And thanks for the info! Will update the code now.

> Multiple accounts

It's definitely something I'd like to add in the future!

**Review by Zebiano — APPROVED** [review]

**Pull request merged**
