### PR TITLE
Add: Fight in More Than Main Tower

### PR DESCRIPTION
**Pull request by delgatojr**
- Add: battleKingsTower function

So far it just battles once in every tower once, except the main tower. I tested it and works. If a tower is closed it does nothing and checks the next one.

### CODE REVIEW

**Comment by delgatojr** [comment]
So how should we do this one? I think we let the battles finish for progression.

-  Should we battle once in each open tower?

- Should we add a new config variable to retry failed battles similar to the campaign one?

- Should we include the main tower to finish battles, and progress through towers as well?

**Comment by Zebiano** [comment]
My answer is "yes" to all of your questions!

**Comment by delgatojr** [comment]
I tested it multiple times and it seems to be working fine. I haven't seen a Limited Offer, but it will probably keep the script waiting forever in "waitBattleFinish". I left an idea of how to solve it, automatically, and left it commented in the code.

**Comment by Zebiano** [comment]
Don't limited offers only pop up when you're on one of the main "tabs" (Campaign, Dark Forest, Ranhron)? Because if they do, they wouldn't be a problem in this case. I'll test it out a bit and see if I get any.

**Comment by delgatojr** [comment]
> 
> 
> Don't limited offers only pop up when you're on one of the main "tabs" (Campaign, Dark Forest, Ranhron)? Because if they do, they wouldn't be a problem in this case. I'll test it out a bit and see if I get any.

Sometimes when you beat a stage it pops up. Like in increments of stage 100s or 50s

**Comment by Zebiano** [comment]
Thank you for this PR!

**Pull request merged**
