### PR TITLE
Fix: Create flags for running the script #7

### PR DESCRIPTION
**Pull request by kevingrillet**
- fix tab > spaces
- flag for device `-d <device>`
- dev: multiple account with flag `-a <account>`  (multiple `.afkscript.tmp` files)

### CODE REVIEW

**Review by delgatojr — COMMENTED** [review]
Great work, sir.
There is a misspelling here: in the elif optarg is nox `device="Bluestacks"` & `printInfo "Usage: ./deoploy.sh [-a <ACCOUNT>] [-d <DEVICE>]"`

**Comment by kevingrillet** [comment]
Oops, my bad. *fixed*

**Comment by Zebiano** [comment]
The only thing I did not quite understand was what value `-a` can be? What do you mean by "account"? I imagine the value can be anything, as it seems you only use it to make different `.tmp` files by naming them.

Also, by giving it a name before the `.`, you're making the files visible, which is not desired. It should be possible to change `tempFile="$OPTARG.afkscript.tmp"` to `tempFile=".afkscript_$OPTARG.tmp"` to fix this, right? Line `337`.

**Comment by kevingrillet** [comment]
Yes `-a` is for account, well, to name the `.tmp` file so i can move it anywhere in the name

**Comment by Zebiano** [comment]
Looks good to me, will test it out later.

**Comment by delgatojr** [comment]
**./deploy.sh -a manny** created .mannyafkscript.tmp 👍 
**./deploy.sh -a manny** again but changed .mannyafkscript.tmp value so it's been over 3 days and did not beat campaign 👎 
I _think_ the `while getopts ":a:d:h" option ;` stuff should be before checkDate gets called.

**Comment by delgatojr** [comment]
**./deploy.sh -h** does print out the help information but it also runs the script.
image

**Comment by kevingrillet** [comment]
Added to #59 to do further testing/improvements

**Pull request closed without merging**
