### PR TITLE
Add: Collect Weekly Quests

### PR DESCRIPTION
**Pull request by delgatojr**
I think basically mirroring the daily quest collecting will work. If there's no weekly chest it doesn't break anything.

### CODE REVIEW

**Review by kevingrillet — CHANGES_REQUESTED** [review]
I think you forgot to uncomment from line 1321, just having a `config.sh` file with nearly everything at `false` work 😄 


<details>
  <summary>afk-daily.json</summary>

```shell
# # CAMPAIGN TAB
# switchTab "Campaign"
# if [ "$doLootAfkChest" == true ]; then lootAfkChest; fi
# if [ "$doChallengeBoss" == true ]; then challengeBoss; fi
# if [ "$doFastRewards" == true ]; then fastRewards; fi
# if [ "$doCollectFriendsAndMercenaries" == true ]; then collectFriendsAndMercenaries; fi
# if [ "$doLootAfkChest" == true ]; then lootAfkChest; fi

# # DARK FOREST TAB
# switchTab "Dark Forest"
# if [ "$doSoloBounties" == true ]; then soloBounties; fi
# if [ "$doTeamBounties" == true ]; then
#     if [ "$doSoloBounties" == true ]; then teamBounties; else teamBounties true; fi
# fi
# if [ "$doArenaOfHeroes" == true ]; then arenaOfHeroes; fi
# if [ "$doLegendsTournament" == true ]; then
#     if [ "$doArenaOfHeroes" == true ]; then legendsTournament; else legendsTournament true; fi
# fi
# if [ "$doKingsTower" == true ]; then kingsTower; fi

# # RANHORN TAB
switchTab "Ranhorn"
# if [ "$doGuildHunts" == true ]; then guildHunts; fi
# if [ "$doTwistedRealmBoss" == true ]; then
#     if [ "$doGuildHunts" == true ]; then twistedRealmBoss; else twistedRealmBoss true; fi
# fi
# if [ "$doBuyFromStore" == true ]; then buyFromStore; fi
# if [ "$doStrenghenCrystal" == true ]; then strenghenCrystal; fi
# if [ "$doCompanionPointsSummon" == true ]; then nobleTavern; fi
# if [ "$doCollectOakPresents" == true ]; then oakInn; fi

# # END
if [ "$doCollectQuestChests" == true ]; then collectQuestChests; fi
# if [ "$doCollectMail" == true ]; then collectMail; fi
# if [ "$doCollectMerchantFreebies" == true ]; then collectMerchants; fi

# # Ends at given location
# sleep 1
# checkWhereToEnd
```

</details>

**Comment by delgatojr** [comment]
> 
> 
> I think you forgot to uncomment from line 1321, just having a `config.sh` file with nearly everything at `false` work 😄
> afk-daily.json

That's a great idea lol I'll be doing it that way from now on

**Comment by Zebiano** [comment]
Looks good to me. Will test out later!

**Comment by Zebiano** [comment]
Thank you for this PR!

**Pull request merged**
