### PR TITLE
Add: Buy Elite Hero Soulstones #49

### PR DESCRIPTION
**Pull request by delgatojr**
Discussion Forum: #49

Probably need a few more rounds of testing the RGBs, since I got different values a few times on the 4th tile. The last RGB I got from the 4th tile worked, and the script **did** buy the soulstones.

I edited the script so it only buys store items then exits, for testing.

* Add: Buy Elite Hero Soulstones

* Add: buyStoreEliteStones to config.sh

* Add: buyStoreEliteStones to README.md

### CODE REVIEW

**Comment by delgatojr** [comment]
image
It only bought the second one.

**Comment by delgatojr** [comment]
image
Bought it with the new RGB value.

**Comment by delgatojr** [comment]
Did not buy the 4tile stone on a second account. The RGB value is different??

**Comment by Zebiano** [comment]
> Did not buy the 4tile stone on a second account. The RGB value is different??

This is still a mystery to me. It's so weird that that is happening...

**Comment by delgatojr** [comment]
I guess I will add on ` || [ "$RGB" == "new RGB" ]` until no new RGBs appear.

**Comment by Zebiano** [comment]
Not the biggest fan of that, but it looks like we have no other choice.

**Comment by delgatojr** [comment]
Yeah, no. I don't see this working this way. I think we wait for tolerances to be added for this feature.

**Comment by Zebiano** [comment]
Let's keep this to the [Discussion](https://github.com/zebscripts/AFK-Daily/discussions/49) instead of a PR while we test for RGB values.

**Pull request closed without merging**
