### PR TITLE
Dev: config.ini

### PR DESCRIPTION
**Pull request by kevingrillet**
- configFile="config.sh" > configFile="config.ini"
- Use $configFile var everywhere

### CODE REVIEW

**Comment by Zebiano** [comment]
Why would I prefer a `.ini` over a `.sh`? What's the benefit?

**Comment by kevingrillet** [comment]
Well, it's just formalism 😉 

> An INI file is a configuration file for computer software that consists of a text-based content with a structure and syntax comprising key–value pairs for properties, and sections that organize the properties.

> An SH file is a script programmed for bash, a type of Unix shell (Bourne-Again SHell).

**Comment by Zebiano** [comment]
Right. I like it!

**Comment by kevingrillet** [comment]
Added to #59 to do further testing/improvements

**Pull request closed without merging**
