### PR TITLE
Fix: 2 settings for Arena and Legends tries #47

### PR DESCRIPTION
**Pull request by kevingrillet**

### CODE REVIEW

**Comment by Zebiano** [comment]
Looks good to me, will test it out later.

**Comment by delgatojr** [comment]
So totalAmountTournamentTries will default to zero, then? Why not just put zero, instead of $((totalAmountArenaTries - 2))

**Comment by Zebiano** [comment]
> So totalAmountTournamentTries will default to zero, then? Why not just put zero, instead of $((totalAmountArenaTries - 2))

Yes, I noticed this already as well and I will most likely default it to `0`. I just want to make sure that it is the way the game works.

**Comment by delgatojr** [comment]
Tested and it hung when arenaHeroesOpponent=5, as that's a previous issue. I changed it to arenaHeroesOpponent=4 and everything worked perfectly.

**Comment by kevingrillet** [comment]
I did put `$((totalAmountArenaTries - 2))` because it's the actual value used, but I can put `0` if you want 😄

**Pull request closed without merging**
